# Generated by Django 6.0 on 2026-02-04 00:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_retweet",
            field=models.BooleanField(
                default=False,
                help_text="Indica se este post é um retweet de outro post",
                verbose_name="É retweet",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="retweet_of",
            field=models.ForeignKey(
                blank=True,
                help_text="Post original sendo retweetado (se aplicável)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="retweets",
                to="posts.post",
                verbose_name="Retweet de",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="retweets_count",
            field=models.IntegerField(
                default=0,
                help_text="Contador de quantas vezes este post foi retweetado",
                verbose_name="Quantidade de retweets",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["is_retweet"], name="posts_post_is_retw_8ebadd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["retweet_of"], name="posts_post_retweet_352e68_idx"
            ),
        ),
    ]
