# Generated by Django 6.0 on 2026-02-06 16:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0003_post_is_retweet_post_retweet_of_post_retweets_count_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="in_reply_to",
            field=models.ForeignKey(
                blank=True,
                help_text="Post ao qual este post está respondendo (se aplicável)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="posts.post",
                verbose_name="Em resposta a",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["in_reply_to"], name="posts_post_in_repl_ca93ea_idx"
            ),
        ),
    ]
