# Generated by Django 6.0 on 2026-02-06 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_post_in_reply_to_post_posts_post_in_repl_ca93ea_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("image", "Imagem"),
                            ("video", "Vídeo"),
                            ("gif", "GIF"),
                        ],
                        help_text="Tipo do arquivo (imagem, vídeo ou GIF)",
                        max_length=10,
                        verbose_name="Tipo de mídia",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Arquivo de mídia (imagem, vídeo ou GIF)",
                        upload_to="post_media/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        help_text="Miniatura do vídeo (gerada automaticamente)",
                        null=True,
                        upload_to="thumbnails/",
                        verbose_name="Thumbnail",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Ordem de exibição da mídia no post",
                        verbose_name="Ordem",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "post",
                    models.ForeignKey(
                        help_text="Post ao qual esta mídia pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="posts.post",
                        verbose_name="Post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mídia do Post",
                "verbose_name_plural": "Mídias dos Posts",
                "ordering": ["order", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["post", "order"], name="posts_postm_post_id_857b22_idx"
                    )
                ],
            },
        ),
    ]
