# Generated by Django 6.0 on 2026-02-08 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0005_postmedia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Poll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.CharField(
                        blank=True,
                        help_text="Pergunta da enquete (opcional, pode estar no conteúdo do post)",
                        max_length=280,
                        verbose_name="Pergunta",
                    ),
                ),
                (
                    "duration_hours",
                    models.IntegerField(
                        default=24,
                        help_text="Duração da enquete em horas (ex: 24, 168)",
                        verbose_name="Duração (horas)",
                    ),
                ),
                (
                    "ends_at",
                    models.DateTimeField(
                        help_text="Data e hora de término da enquete",
                        verbose_name="Termina em",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "post",
                    models.OneToOneField(
                        help_text="Post ao qual esta enquete pertence",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll",
                        to="posts.post",
                        verbose_name="Post",
                    ),
                ),
            ],
            options={
                "verbose_name": "Enquete",
                "verbose_name_plural": "Enquetes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PollOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.CharField(
                        help_text="Texto da opção de voto",
                        max_length=100,
                        verbose_name="Texto",
                    ),
                ),
                (
                    "votes",
                    models.IntegerField(
                        default=0,
                        help_text="Quantidade de votos nesta opção",
                        verbose_name="Votos",
                    ),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0,
                        help_text="Ordem de exibição da opção",
                        verbose_name="Ordem",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="posts.poll",
                        verbose_name="Enquete",
                    ),
                ),
            ],
            options={
                "verbose_name": "Opção de Enquete",
                "verbose_name_plural": "Opções de Enquete",
                "ordering": ["order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="PollVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "voted_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Votado em"),
                ),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_votes",
                        to="posts.polloption",
                        verbose_name="Opção",
                    ),
                ),
                (
                    "poll",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_votes",
                        to="posts.poll",
                        verbose_name="Enquete",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_votes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Voto em Enquete",
                "verbose_name_plural": "Votos em Enquetes",
                "ordering": ["-voted_at"],
            },
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(fields=["post"], name="posts_poll_post_id_3aab8f_idx"),
        ),
        migrations.AddIndex(
            model_name="poll",
            index=models.Index(
                fields=["ends_at"], name="posts_poll_ends_at_60526b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="polloption",
            index=models.Index(
                fields=["poll", "order"], name="posts_pollo_poll_id_b000b9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pollvote",
            index=models.Index(
                fields=["poll", "user"], name="posts_pollv_poll_id_6e53d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="pollvote",
            index=models.Index(
                fields=["option"], name="posts_pollv_option__c66956_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="pollvote",
            unique_together={("poll", "user")},
        ),
    ]
