# Generated by Django 6.0 on 2026-02-10 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0006_poll_polloption_pollvote_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nome do local (ex: 'São Paulo, Brasil')",
                        max_length=200,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Coordenada de latitude (-90 a 90)",
                        max_digits=9,
                        null=True,
                        verbose_name="Latitude",
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        help_text="Coordenada de longitude (-180 a 180)",
                        max_digits=9,
                        null=True,
                        verbose_name="Longitude",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Localização",
                "verbose_name_plural": "Localizações",
                "ordering": ["name"],
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="posts_locat_latitud_2a860b_idx",
                    ),
                    models.Index(fields=["name"], name="posts_locat_name_933a30_idx"),
                ],
                "unique_together": {("latitude", "longitude")},
            },
        ),
        migrations.AddField(
            model_name="post",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Local onde o post foi criado",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="posts.location",
                verbose_name="Localização",
            ),
        ),
    ]
