# Generated by Django 6.0 on 2026-02-11 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0007_location_post_location"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="scheduled_for",
            field=models.DateTimeField(
                blank=True,
                help_text="Data e hora em que o post será publicado. Se null, publica imediatamente.",
                null=True,
                verbose_name="Agendado para",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["scheduled_for"], name="posts_post_schedul_efb374_idx"
            ),
        ),
    ]
