# Generated by Django 6.0 on 2026-02-13 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_post_scheduled_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, help_text='Data e hora de publicação. Se null, publica imediatamente.', null=True, verbose_name='Agendado para'),
        ),
    ]
