# Generated by Django 6.0 on 2026-02-13 20:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_scheduled_for'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Número de vezes que o post foi visualizado', verbose_name='Visualizações'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['views_count'], name='posts_post_views_c_d9bd13_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-views_count'], name='posts_post_views_c_0f79e1_idx'),
        ),
    ]
