# Generated by Django 6.0 on 2026-02-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0010_post_views_count_post_posts_post_views_c_d9bd13_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hashtag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Nome da hashtag (sem #, ex: 'python')",
                        max_length=100,
                        unique=True,
                        verbose_name="Nome",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Versão normalizada da hashtag",
                        max_length=100,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "posts_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Número de posts que usam esta hashtag",
                        verbose_name="Contagem de posts",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criado em"),
                ),
            ],
            options={
                "verbose_name": "Hashtag",
                "verbose_name_plural": "Hashtags",
                "ordering": ["-posts_count", "name"],
                "indexes": [
                    models.Index(fields=["name"], name="posts_hasht_name_1acbc9_idx"),
                    models.Index(fields=["slug"], name="posts_hasht_slug_ef5e02_idx"),
                    models.Index(
                        fields=["-posts_count"], name="posts_hasht_posts_c_01b123_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="posts_hasht_created_bc3012_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="post",
            name="hashtags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Hashtags extraídas do conteúdo",
                related_name="posts",
                to="posts.hashtag",
                verbose_name="Hashtags",
            ),
        ),
    ]
