# Generated by Django 6.0 on 2026-02-17 22:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0011_hashtag_post_hashtags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("like", "Curtida"),
                            ("retweet", "Retweet"),
                            ("reply", "Resposta"),
                            ("follow", "Seguidor"),
                            ("mention", "Menção"),
                        ],
                        max_length=20,
                        verbose_name="Tipo de notificação",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="Indica se a notificação foi lida",
                        verbose_name="Lida",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Criada em"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="Usuário que gerou a notificação",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications_sent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Autor da ação",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        help_text="Post relacionado à notificação (se aplicável)",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="posts.post",
                        verbose_name="Post relacionado",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        help_text="Usuário que recebe a notificação",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Destinatário",
                    ),
                ),
            ],
            options={
                "verbose_name": "Notificação",
                "verbose_name_plural": "Notificações",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="posts_notif_recipie_51632d_idx",
                    ),
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="posts_notif_recipie_7d44a8_idx",
                    ),
                    models.Index(
                        fields=["actor"], name="posts_notif_actor_i_4de1ac_idx"
                    ),
                    models.Index(
                        fields=["notification_type"],
                        name="posts_notif_notific_6df94b_idx",
                    ),
                ],
                "unique_together": {
                    ("recipient", "actor", "notification_type", "post")
                },
            },
        ),
    ]
