# Generated by Django 6.0 on 2026-03-11 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0012_notification"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="comment",
            name="posts_comme_post_id_7929fe_idx",
        ),
        migrations.DeleteModel(
            name="Comment",
        ),
    ]
