# Generated by Django 6.0 on 2026-01-30 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="banner",
            field=models.ImageField(
                blank=True,
                help_text="Imagem de capa do perfil do usuário",
                null=True,
                upload_to="banners/",
                verbose_name="Banner do perfil",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="Data de nascimento do usuário",
                null=True,
                verbose_name="Data de nascimento",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Localização do usuário (cidade, país, etc)",
                max_length=100,
                verbose_name="Localização",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="website",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL do site ou blog pessoal",
                verbose_name="Site pessoal",
            ),
        ),
    ]
